### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-TrainGroups#1]
The game crash (opened game go back to maim menu) when I'm using the CTRL-C selection tool over water!

---
 ...
 229.879 Error MainLoop.cpp:1284: Exception at tick 63077673: The mod Train Groups (1.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event TrainGroups::on_player_setup_blueprint (ID 69)
__TrainGroups__/control.lua:87: attempt to get length of local 'entities' (a nil value)
stack traceback:
	__TrainGroups__/control.lua:87: in function <__TrainGroups__/control.lua:69>
---

Thanks

**Comment by raiguard** [comment]
Ack, I specifically checked the docs to see if this could be `nil`, but I misread it.
