### ISSUE TITLE
Cannot use ctrl+F on the train menu.

### ISSUE THREAD

**Issue by Nebisan** [raiguard/Factorio-TrainGroups#24]
Hello, I noticed that with the mod installed, ctrl+F no longer works in the trains overview window or stops overview window. I don't think this has been mentioned in a previous issue, so I just wanted to bring it up. Would it be possible to make it so this shortcut works with the mod? I'm playing bobs/angels and as you can imagine, I have to use the quick search a lot. Thanks.

**Comment by raiguard** [comment]
Thanks for the report. This is actually a bug in the base game and I have fixed it for the next patch.
